### ISSUE TITLE
createQuizAb() 하드코딩부분 해결 및 리팩토링

### ISSUE THREAD

**Issue by wonjaeban** [HangHae99Zzz/RoomEscape_BE#152]
**Description**
QuizService에서 createQuizAb()에서 하드 코딩된 부분들을 제거하고 바꿨습니다.

**Todo**
- [x] String 객체 및 Int들을 상수화시키기.
- [x] 반복되는 로직 메서드로 빼기(createEven, createOdd)
- [x] String 생성시 + 연산자 사용하지 않고 StringBuilder 사용하기.

**ETC**
기타사항

**Comment by wonjaeban** [comment]
[main](https://github.com/HangHae99Zzz/RoomEscape_BE) ([#151](https://github.com/HangHae99Zzz/RoomEscape_BE/pull/151))
해당 커밋으로 해결함.
