### ISSUE TITLE
퀴즈 생성 시간 테스트 코드 작성

### ISSUE THREAD

**Issue by wonjaeban** [HangHae99Zzz/RoomEscape_BE#75]
**Description**
테스트 코드를 활용하여 QuizService의 getQuizAa(), getQuizAb(), getQuizBa(), getQuizBb(), getQuizCa()의 시간을 측정하는 테스트 코드 작성할 것.

**Todo**
- [x] getQuizAa() 테스트 코드
- [x] getQuizAb() 테스트 코드
- [x] getQuizBa() 테스트 코드
- [x] getQuizBb() 테스트 코드
- [x] getQuizCa() 테스트 코드

**ETC**
기타사항

**Comment by wonjaeban** [comment]
각각의 퀴즈 생성 로직의 실행시간을 측정 결과
실행시간(m) : 0.002초
실행시간(m) : 0.004초
실행시간(m) : 0.063초
실행시간(m) : 0.0초
실행시간(m) : 0.0초
로 나왔다. 하지만 여기서 로직을 더 효율적으로 짠다고 실행시간이 획기적으로 줄어들 것이라 생각되지 않는다. 따라서 시간을 줄이는 것에만 집중하는 것이 아니라 코딩을 잘 짜는 것(하드코딩 줄이기)에 초점을 두기로 하였다.
